
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							STAT-BASED BONUS SPELLS
//__________________________________________________________________________________
//__________________________________________________________________________________


// -----------------------------
// ABILITY SCORE BONUS SPELLS
// -----------------------------

// ***** zero out MXSPLWIS, use this method for all priests - and paladins and rangers, too

DEFINE_ACTION_FUNCTION ability_bonus_spells BEGIN 

APPEND ~splprot.2da~ ~D5_INT_IS%TAB%38%TAB%-1%TAB%1~ UNLESS ~D5_INT_IS~
APPEND ~splprot.2da~ ~D5_CHR_IS%TAB%42%TAB%-1%TAB%1~ UNLESS ~D5_CHR_IS~

COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols   
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ 
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_INT_IS~ BEGIN
	    SET int_slots = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_CHR_IS~ BEGIN
	    SET chr_slots = %row%
	  END
	END
BUT_ONLY

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__abil_spells.d5~) THEN BEGIN

//COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slot1.spl~ ~override/d5absp1.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5absp1.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~d5abspw~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 19 parameter2 = 105 timing = 0 duration = 1 STR_VAR resource = ~d5absp1~ END
//COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slot1.spl~ ~override/d5absp2.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5absp2.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 5 parameter2 = 5 timing = 9 STR_VAR resource = ~d5abspb~ END
//COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slot1.spl~ ~override/d5absp3.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5absp3.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 19 parameter2 = 5 timing = 9 STR_VAR resource = ~d5absps~ END

COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.eff~ ~override/d5abspw.eff~
	WRITE_ASCII 0x30 ~d5abspw~ #8
COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.eff~ ~override/d5abspb.eff~
	WRITE_ASCII 0x30 ~d5abspb~ #8
COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.eff~ ~override/d5absps.eff~
	WRITE_ASCII 0x30 ~d5absps~ #8

//COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.spl~ ~override/d5absp.spl~

COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.spl~ ~override/d5abspw.spl~ 	// 	spell slot modifications for wizards
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = 129 target = 1 timing = 1 STR_VAR resource = ~d5intwo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 17 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 18 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 19 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intws~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 20 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 21 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 22 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 23 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intww~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 24 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 25 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwy~ END
COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.spl~ ~override/d5abspb.spl~ 	// 	spell slot modifications for bards
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = 133 target = 1 timing = 1 STR_VAR resource = ~d5chrbo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 17 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 18 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 19 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbs~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 20 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 21 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 22 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 23 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 24 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbx~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 25 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrby~ END
COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.spl~ ~override/d5absps.spl~ 	// 	spell slot modifications for sorcerers
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = 133 target = 1 timing = 1 STR_VAR resource = ~d5chrso~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 17 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 18 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 19 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrss~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 20 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrst~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 21 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 22 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 23 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 24 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 25 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsy~ END

  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwo.spl~ // <16
    PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intw%seq%~ END
    END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwp.spl~ // 16
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intw%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 1 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwq.spl~ // 17
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intw%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 3 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwr.spl~ // 18
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intw%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 7 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intws.spl~ // 19
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intw%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 15 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwt.spl~ // 20
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intw%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 7 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 8 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwu.spl~ // 21
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intw%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 15 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 16 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwv.spl~ // 22
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intw%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 31 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 32 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intww.spl~ // 23
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intw%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 63 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 64 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwx.spl~ // 24
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intw%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 127 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 128 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwy.spl~ // 25
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intw%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 255 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 256 target = 1 timing = 9 duration = 0 END

  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbo.spl~ // <16
    PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrb%seq%~ END
    END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbp.spl~ // 16
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrb%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 1 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbq.spl~ // 17
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrb%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 3 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbr.spl~ // 18
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrb%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 7 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbs.spl~ // 19
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrb%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 15 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbt.spl~ // 20
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrb%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 7 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 8 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbu.spl~ // 21
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrb%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 15 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 16 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbv.spl~ // 22
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrb%seq%~ END
    END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 31 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 32 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbw.spl~ // 23
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrb%seq%~ END
    END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 63 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 64 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbx.spl~ // 24
    PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrb%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 127 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 128 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrby.spl~ // 25
    PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrb%seq%~ END
    END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 255 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 1 parameter2 = 256 target = 1 timing = 9 duration = 0 END

  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrso.spl~ // <16
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrs%seq%~ END
    END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsp.spl~ // 16
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrs%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 30 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsq.spl~ // 17
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrs%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 30 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsr.spl~ // 18
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrs%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 30 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrss.spl~ // 19
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrs%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 30 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrst.spl~ // 20
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrs%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 3 parameter2 = 30 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsu.spl~ // 21
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrs%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 4 parameter2 = 3 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 3 parameter2 = 12 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 16 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsv.spl~ // 22
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrs%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 4 parameter2 = 7 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 3 parameter2 = 24 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 32 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsw.spl~ // 23
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrs%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 4 parameter2 = 15 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 3 parameter2 = 48 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 64 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsx.spl~ // 24
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrs%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 4 parameter2 = 31 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 3 parameter2 = 96 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 128 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsy.spl~ // 25
	PATCH_FOR_EACH seq IN o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chrs%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 4 parameter2 = 63 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 3 parameter2 = 192 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = 2 parameter2 = 256 target = 1 timing = 9 duration = 0 END


// 		only sorcerer bonuses - wild mage is in kitlist so will add wizard bonuses below
ACTION_IF FILE_EXISTS_IN_GAME ~clabma01.2da~ BEGIN
	APPEND ~clabma01.2da~ ~XTRA_SPL    AP_D5ABSP3  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
	 
ACTION_IF FILE_EXISTS_IN_GAME ~clabba01.2da~ BEGIN
	APPEND ~clabba01.2da~ ~XTRA_SPL    AP_D5ABSP2  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END

COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS 10 rows
  FOR (row = 3 ; row < rows ; ++row) BEGIN
	READ_2DA_ENTRY %row% 1 10 modname
	READ_2DA_ENTRY %row% 5 10 modclab
	READ_2DA_ENTRY %row% 8 10 modclass
    PATCH_IF (FILE_EXISTS_IN_GAME ~%modclab%.2da~) BEGIN
	  PATCH_IF (%modclass% = 1) AND !(~%modname%~ STRING_MATCHES_REGEXP ~C0SA+~ = 0) AND !(~%modclab%~ STRING_EQUAL_CASE ~D5ACNST~) AND !(~%modclab%~ STRING_EQUAL_CASE ~D5_MANA~) BEGIN	// mage kits
	    INNER_ACTION BEGIN
		  APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ABSP1  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
	    END
	  END
	  PATCH_IF (%modclass% = 5) AND !(~%modname%~ STRING_MATCHES_REGEXP ~C0SA+~ = 0) BEGIN 	// bard kits
	    INNER_ACTION BEGIN
		  APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ABSP2  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
	    END
	  END
	  PATCH_IF (%modclass% = 19) AND !(~%modname%~ STRING_MATCHES_REGEXP ~C0SA+~ = 0) BEGIN 	// sorcerer kits
	    INNER_ACTION BEGIN
		  APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ABSP3  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
	    END
	  END
	  PATCH_IF (%modclass% = 1) OR (%modclass% = 5) OR (%modclass% = 19) OR (%modclass% = 7) OR (%modclass% = 10) OR (%modclass% = 13) OR (%modclass% = 14) OR (%modclass% = 17) BEGIN
	    PATCH_IF (~%modname%~ STRING_MATCHES_REGEXP ~C0SA+~ = 0) BEGIN	// shadow adept arcane kits
		  INNER_ACTION BEGIN
		    APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ZISLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
		    APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ZJSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
		  END
	    END
	  END
	END
  END
BUT_ONLY


// CHA bonus spells for multisorc_____________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5sorc.2da~) BEGIN

  LAM semi_cha_slots

  COPY_EXISTING ~d5xrfsh.spl~ ~override~
	PHP_EACH cha_nums_lets AS cha => slot BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 10 opcode = 326 target = 1 parameter1 = %cha% parameter2 = 132 timing = 1 STR_VAR resource = EVAL ~d5chas%slot%~ END
	END
	PHP_EACH cha_nums_lets AS cha => slot BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 1 opcode = 321 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chas%slot%~ END
	END
  IF_EXISTS BUT_ONLY

END

// fix multisorc spell table just in case_____________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~qdtnb_mcsrc.qd~) BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5xltsr.spl~) BEGIN
    DELETE ~d5xltsr.spl~
  END
  LAF arcane_casting_slots STR_VAR slot_table = ~mxsplsrc~ table_spl = ~d5xltsr~ END
END


// CHA bonus spells for manasorc______________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_mana.2da~) BEGIN

  LAM semi_cha_slots

  COPY_EXISTING ~d5mrfrsh.spl~ ~override~
	PHP_EACH cha_nums_lets AS cha => slot BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 10 opcode = 326 target = 1 parameter1 = %cha% parameter2 = %chr_slots% timing = 1 STR_VAR resource = EVAL ~d5cham%slot%~ END
	END
	PHP_EACH cha_nums_lets AS cha => slot BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 1 opcode = 321 target = 1 timing = 1 STR_VAR resource = EVAL ~d5cham%slot%~ END
	END
  IF_EXISTS BUT_ONLY

END


COPY ~%MOD_FOLDER%/lib/semi_spont/d5_marker.d5~ ~override/d5__abil_spells.d5~

END


// WIS bonus spells for clerics, druids, paladins and rangers
//
COPY ~%MOD_FOLDER%/data/stats/mxsplwis_0.2da~ ~override/mxsplwis.2da~

//STRING_SET 9586 @20005 

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5absp4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~d5abspc~ END

COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.eff~ ~override/d5abspc.eff~
	WRITE_ASCII 0x30 ~d5abspc~ #8

APPEND ~splprot.2da~ ~D5_WIS_IS%TAB%39%TAB%-1%TAB%1~ UNLESS ~D5_WIS_IS~

COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols   
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ 
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_WIS_IS~ BEGIN
	    SET wis_slots = %row%
	  END
	END
BUT_ONLY

COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.spl~ ~override/d5abspc.spl~ 	// 	spell slot modifications for paladins and rangers
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 13 parameter2 = 131 target = 1 timing = 1 STR_VAR resource = ~d5wiscl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 13 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wiscm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 14 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wiscn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 15 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wisco~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wiscp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 17 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wiscq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 18 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wiscr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 19 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wiscs~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 20 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wisct~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 21 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wiscu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 22 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wiscv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 23 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wiscw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 24 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wiscx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 25 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wiscy~ END

  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscl.spl~ // <13
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscm.spl~ // 13
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 1 parameter2 = 1 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscn.spl~ // 14
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 2 parameter2 = 1 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wisco.spl~ // 15
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 2 parameter2 = 1 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 1 parameter2 = 2 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscp.spl~ // 16
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 2 parameter2 = 3 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscq.spl~ // 17
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 2 parameter2 = 3 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 1 parameter2 = 4 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscr.spl~ // 18
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 2 parameter2 = 7 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 1 parameter2 = 8 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscs.spl~ // 19
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 3 parameter2 = 1 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 2 parameter2 = 6 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 1 parameter2 = 8 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wisct.spl~ // 20
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 3 parameter2 = 3 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 2 parameter2 = 12 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscu.spl~ // 21
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 3 parameter2 = 7 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 2 parameter2 = 8 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 1 parameter2 = 16 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscv.spl~ // 22
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 3 parameter2 = 15 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 2 parameter2 = 16 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscw.spl~ // 23
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 4 parameter2 = 1 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 3 parameter2 = 14 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 2 parameter2 = 16 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 1 parameter2 = 32 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscx.spl~ // 24
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 4 parameter2 = 1 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 3 parameter2 = 30 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 2 parameter2 = 32 target = 1 timing = 9 duration = 0 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wiscy.spl~ // 25
	PATCH_FOR_EACH seq IN l m n o p q r s t u v w x y BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisc%seq%~ END
    END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 4 parameter2 = 1 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 3 parameter2 = 62 target = 1 timing = 9 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = 1 parameter2 = 64 target = 1 timing = 9 duration = 0 END

ACTION_IF FILE_EXISTS_IN_GAME ~clabpr01.2da~ BEGIN
	APPEND ~clabpr01.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabdr01.2da~ BEGIN
	APPEND ~clabdr01.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabpa01.2da~ BEGIN
	APPEND ~clabpa01.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabrn01.2da~ BEGIN
	APPEND ~clabrn01.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END

COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS 10 rows
  FOR (row = 3 ; row < rows ; ++row) BEGIN
	READ_2DA_ENTRY %row% 1 10 modname
	READ_2DA_ENTRY %row% 5 10 modclab
	READ_2DA_ENTRY %row% 8 10 modclass
	PATCH_IF (%modclass% = 21) OR (%modclass% = 3) OR (%modclass% = 11) OR (%modclass% = 6) OR (%modclass% = 12) BEGIN	// divine kits
	  INNER_ACTION BEGIN
		APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
	  END
	END
  END
BUT_ONLY

// adjust joinable NPC slots__________________________________________________________
//
LAM JOINABLE_NPC_ARRAYS

/*
ACTION_PHP_EACH JOINABLE_NPC_ARRAY AS cre => dv BEGIN
//  PRINT ~%cre% = non-joinable~ 
  COPY_EXISTING ~%cre%~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
      GET_OFFSET_ARRAY slot_array CRE_V10_SPELL_MEM_INFO
      PHP_EACH slot_array AS inf => slot_off BEGIN
        READ_SHORT slot_off spl_level
        READ_SHORT (slot_off + 0x02) spl_slots
        READ_SHORT (slot_off + 0x06) spl_type
        PATCH_IF (spl_slots > 0) AND (spl_level < 7) AND !(spl_type = 2) BEGIN
          WRITE_SHORT (slot_off + 0x02) (spl_slots + 2)
        END
      END
    END
  BUT_ONLY
END
//____________________________________________________________________________________
*/

END 	//	end define function